/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.udea.surax.vista;

/**
 * 
 * @author Jose D. Gómez M.
 * @author Hector A. Güiza O
 * @author Luis D. Martínez G.
 * 
 */
public class EstudianteVista extends javax.swing.JFrame {

    /**
     * Creates new form PersonaVista
     */
    public EstudianteVista() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/icon.png")).getImage());
        setTitle("Surax");
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipoPersona = new javax.swing.ButtonGroup();
        btnGroupZona = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JLabel();
        btnAgregarEstudiante = new javax.swing.JLabel();
        btnBuscarEstudiante = new javax.swing.JLabel();
        btnEliminarEstudiante = new javax.swing.JLabel();
        btnLimpiarVentana = new javax.swing.JLabel();
        msjIndicacion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelInfoPersonal1 = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        inputId = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        inputTel = new javax.swing.JTextField();
        inputOcupacion = new javax.swing.JTextField();
        inputOptionSexo = new javax.swing.JComboBox<>();
        inputNumEdad = new javax.swing.JSpinner();
        inputNumEstrato = new javax.swing.JSpinner();
        inputOptionEnfermedad = new javax.swing.JComboBox<>();
        inputOptionDiscapacidad = new javax.swing.JComboBox<>();
        inputOptionEstadoCivil = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        labelDatosEstudio = new javax.swing.JLabel();
        labelDir = new javax.swing.JLabel();
        inputOptionDpto = new javax.swing.JComboBox<>();
        inputOptionMpio = new javax.swing.JComboBox<>();
        inputDir = new javax.swing.JTextField();
        inputCodPostal = new javax.swing.JTextField();
        labelZona = new javax.swing.JLabel();
        inputRdUrbana = new javax.swing.JRadioButton();
        inputRdRural = new javax.swing.JRadioButton();
        inputAcudiente = new javax.swing.JTextField();
        inputPrograma = new javax.swing.JTextField();
        inputRdPublica = new javax.swing.JRadioButton();
        inputRdPrivada = new javax.swing.JRadioButton();
        inputInstitucion1 = new javax.swing.JTextField();
        jSeparator = new javax.swing.JSeparator();
        btnActualizaInfo = new javax.swing.JLabel();
        btnCotizarPoliza = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setAutoscrolls(true);
        jPanel5.setPreferredSize(new java.awt.Dimension(1280, 980));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/back_icon.png"))); // NOI18N
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAgregarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/agregar_estudiante.png"))); // NOI18N
        btnAgregarEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarEstudiante.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/agregar_estudiante_disabled.png"))); // NOI18N
        btnAgregarEstudiante.setEnabled(false);

        btnBuscarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/buscar_estudiante.png"))); // NOI18N
        btnBuscarEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarEstudiante.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/buscar_estudiante_disabled.png"))); // NOI18N
        btnBuscarEstudiante.setEnabled(false);

        btnEliminarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/eliminar_estudiante.png"))); // NOI18N
        btnEliminarEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEstudiante.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/eliminar_estudiante_disabled.png"))); // NOI18N
        btnEliminarEstudiante.setEnabled(false);

        btnLimpiarVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/trash_icon.png"))); // NOI18N
        btnLimpiarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarVentana.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/trash_icon_disabled.png"))); // NOI18N

        msjIndicacion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        msjIndicacion.setForeground(new java.awt.Color(112, 112, 112));
        msjIndicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msjIndicacion.setText("Espacio para mensajes o indicaciones");

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setPreferredSize(new java.awt.Dimension(614, 744));

        labelInfoPersonal1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelInfoPersonal1.setForeground(new java.awt.Color(0, 163, 224));
        labelInfoPersonal1.setText("Información Personal*");

        inputNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112), 2), "Nombre Completo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        inputNombre.setVerifyInputWhenFocusTarget(false);
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });

        inputId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputId.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112), 2), "Número de Documento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        inputId.setVerifyInputWhenFocusTarget(false);
        inputId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdActionPerformed(evt);
            }
        });

        inputEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112), 2), "Correo Electrónico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        inputEmail.setVerifyInputWhenFocusTarget(false);
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });

        inputTel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputTel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112), 2), "Número de Teléfono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        inputTel.setVerifyInputWhenFocusTarget(false);
        inputTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelActionPerformed(evt);
            }
        });

        inputOcupacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputOcupacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112), 2), "Ocupación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        inputOcupacion.setVerifyInputWhenFocusTarget(false);
        inputOcupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputOcupacionActionPerformed(evt);
            }
        });

        inputOptionSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sexo ------------", "Hombre", "Mujer", "Otro" }));
        inputOptionSexo.setBorder(null);
        inputOptionSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputOptionSexoActionPerformed(evt);
            }
        });

        inputNumEdad.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112), 2), "Edad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        inputNumEdad.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        inputNumEstrato.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112), 2), "Estrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        inputNumEstrato.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        inputOptionEnfermedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enfermedades ------------", "Hombre", "Mujer", "Otro" }));
        inputOptionEnfermedad.setBorder(null);
        inputOptionEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputOptionEnfermedadActionPerformed(evt);
            }
        });

        inputOptionDiscapacidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Discapacidad ------------", "Hombre", "Mujer", "Otro" }));
        inputOptionDiscapacidad.setBorder(null);
        inputOptionDiscapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputOptionDiscapacidadActionPerformed(evt);
            }
        });

        inputOptionEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado Civil ------------", "Hombre", "Mujer", "Otro" }));
        inputOptionEstadoCivil.setBorder(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputTel)
                            .addComponent(inputOptionSexo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelInfoPersonal1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                            .addComponent(inputId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputOcupacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputOptionEnfermedad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputOptionDiscapacidad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputOptionEstadoCivil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(74, 74, 74))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(inputNumEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputNumEstrato)
                        .addGap(196, 196, 196))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInfoPersonal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputTel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputOptionSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNumEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNumEstrato, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputOptionEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputOptionDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputOptionEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(java.awt.Color.white);

        labelDatosEstudio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDatosEstudio.setForeground(new java.awt.Color(0, 163, 224));
        labelDatosEstudio.setText("Datos de Estudio*");

        labelDir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDir.setForeground(new java.awt.Color(0, 163, 224));
        labelDir.setText("Dirección*");

        inputOptionDpto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Departamento ------------", "Hombre", "Mujer", "Otro" }));
        inputOptionDpto.setBorder(null);
        inputOptionDpto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputOptionDptoActionPerformed(evt);
            }
        });

        inputOptionMpio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Municipio ------------", "Hombre", "Mujer", "Otro" }));
        inputOptionMpio.setBorder(null);
        inputOptionMpio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputOptionMpioActionPerformed(evt);
            }
        });

        inputDir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputDir.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112), 2), "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        inputDir.setVerifyInputWhenFocusTarget(false);
        inputDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDirinputNombreActionPerformed(evt);
            }
        });

        inputCodPostal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputCodPostal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112), 2), "Código Postal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        inputCodPostal.setVerifyInputWhenFocusTarget(false);
        inputCodPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCodPostalinputNombreActionPerformed(evt);
            }
        });

        labelZona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelZona.setForeground(new java.awt.Color(0, 163, 224));
        labelZona.setText("Zona*");

        btnGroupZona.add(inputRdUrbana);
        inputRdUrbana.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputRdUrbana.setText("Urbana");
        inputRdUrbana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRdUrbanaActionPerformed(evt);
            }
        });

        btnGroupZona.add(inputRdRural);
        inputRdRural.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputRdRural.setText("Rural");
        inputRdRural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRdRuralActionPerformed(evt);
            }
        });

        inputAcudiente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputAcudiente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112), 2), "Acudiente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        inputAcudiente.setVerifyInputWhenFocusTarget(false);
        inputAcudiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAcudienteActionPerformed(evt);
            }
        });

        inputPrograma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputPrograma.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112), 2), "Programa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        inputPrograma.setVerifyInputWhenFocusTarget(false);
        inputPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputProgramaActionPerformed(evt);
            }
        });

        btnGroupZona.add(inputRdPublica);
        inputRdPublica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputRdPublica.setLabel("Pública");
        inputRdPublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRdPublicaActionPerformed(evt);
            }
        });

        btnGroupZona.add(inputRdPrivada);
        inputRdPrivada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputRdPrivada.setSelected(true);
        inputRdPrivada.setLabel("Privada");
        inputRdPrivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRdPrivadaActionPerformed(evt);
            }
        });

        inputInstitucion1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputInstitucion1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112), 2), "Institución", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(112, 112, 112))); // NOI18N
        inputInstitucion1.setVerifyInputWhenFocusTarget(false);
        inputInstitucion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputInstitucion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDir, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputInstitucion1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(inputRdPublica, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputRdPrivada, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelDatosEstudio)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(inputOptionDpto, javax.swing.GroupLayout.Alignment.LEADING, 0, 440, Short.MAX_VALUE)
                        .addComponent(inputOptionMpio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputDir, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(inputCodPostal, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(inputRdUrbana, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputRdRural, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(inputAcudiente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                        .addComponent(labelZona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(labelDir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputOptionDpto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(inputOptionMpio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputDir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelZona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputRdUrbana, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputRdRural, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(labelDatosEstudio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputInstitucion1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputRdPublica, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputRdPrivada, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputAcudiente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnActualizaInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/act_informacion.png"))); // NOI18N
        btnActualizaInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizaInfo.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/act_informacion_disabled.png"))); // NOI18N
        btnActualizaInfo.setEnabled(false);

        btnCotizarPoliza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/cotizar_poliza.png"))); // NOI18N
        btnCotizarPoliza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCotizarPoliza.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/cotizar_poliza_disabled.png"))); // NOI18N
        btnCotizarPoliza.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(msjIndicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btnActualizaInfo)
                .addGap(151, 151, 151)
                .addComponent(btnCotizarPoliza)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnVolver)
                .addGap(27, 27, 27)
                .addComponent(btnAgregarEstudiante)
                .addGap(86, 86, 86)
                .addComponent(btnBuscarEstudiante)
                .addGap(86, 86, 86)
                .addComponent(btnEliminarEstudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarVentana)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msjIndicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizaInfo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCotizarPoliza, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25))
        );

        jScrollPane1.setViewportView(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputOptionDiscapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputOptionDiscapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputOptionDiscapacidadActionPerformed

    private void inputOptionEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputOptionEnfermedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputOptionEnfermedadActionPerformed

    private void inputOcupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputOcupacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputOcupacionActionPerformed

    private void inputTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelActionPerformed

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void inputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputOptionSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputOptionSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputOptionSexoActionPerformed

    private void inputRdRuralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRdRuralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRdRuralActionPerformed

    private void inputRdUrbanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRdUrbanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRdUrbanaActionPerformed

    private void inputCodPostalinputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCodPostalinputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCodPostalinputNombreActionPerformed

    private void inputDirinputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDirinputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDirinputNombreActionPerformed

    private void inputOptionMpioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputOptionMpioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputOptionMpioActionPerformed

    private void inputOptionDptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputOptionDptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputOptionDptoActionPerformed

    private void inputAcudienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAcudienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAcudienteActionPerformed

    private void inputProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputProgramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputProgramaActionPerformed

    private void inputRdPublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRdPublicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRdPublicaActionPerformed

    private void inputRdPrivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRdPrivadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRdPrivadaActionPerformed

    private void inputInstitucion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputInstitucion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputInstitucion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudianteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudianteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudianteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudianteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudianteVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnActualizaInfo;
    private javax.swing.JLabel btnAgregarEstudiante;
    private javax.swing.JLabel btnBuscarEstudiante;
    private javax.swing.JLabel btnCotizarPoliza;
    private javax.swing.JLabel btnEliminarEstudiante;
    private javax.swing.ButtonGroup btnGroupTipoPersona;
    private javax.swing.ButtonGroup btnGroupZona;
    private javax.swing.JLabel btnLimpiarVentana;
    private javax.swing.JLabel btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField inputAcudiente;
    private javax.swing.JTextField inputCodPostal;
    private javax.swing.JTextField inputDir;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputInstitucion1;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JSpinner inputNumEdad;
    private javax.swing.JSpinner inputNumEstrato;
    private javax.swing.JTextField inputOcupacion;
    private javax.swing.JComboBox<String> inputOptionDiscapacidad;
    private javax.swing.JComboBox<String> inputOptionDpto;
    private javax.swing.JComboBox<String> inputOptionEnfermedad;
    private javax.swing.JComboBox<String> inputOptionEstadoCivil;
    private javax.swing.JComboBox<String> inputOptionMpio;
    private javax.swing.JComboBox<String> inputOptionSexo;
    private javax.swing.JTextField inputPrograma;
    private javax.swing.JRadioButton inputRdPrivada;
    private javax.swing.JRadioButton inputRdPublica;
    private javax.swing.JRadioButton inputRdRural;
    private javax.swing.JRadioButton inputRdUrbana;
    private javax.swing.JTextField inputTel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel labelDatosEstudio;
    private javax.swing.JLabel labelDir;
    private javax.swing.JLabel labelInfoPersonal1;
    private javax.swing.JLabel labelZona;
    private javax.swing.JLabel msjIndicacion;
    // End of variables declaration//GEN-END:variables
}
