/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.udea.surax.vista;

import co.edu.udea.surax.modelo.EstudianteModelo;
import co.edu.udea.surax.modelo.PersonaModelo;
import co.edu.udea.surax.modelo.PolizaModelo;
import co.edu.udea.surax.modelo.Utils;
import co.edu.udea.surax.modelo.VehiculoModelo;
import co.edu.udea.surax.vista.*;
import java.util.ArrayList;

/**
 * 
 * @author Jose D. Gómez M.
 * @author Hector A. Güiza O
 * @author Luis D. Martínez G.
 * 
 */
public class Surax extends javax.swing.JFrame {
    
    ArrayList<Object> data;
    ArrayList<PersonaModelo> personas;
    ArrayList<VehiculoModelo> vehiculos;
    ArrayList<EstudianteModelo> estudiantes;
    ArrayList<PolizaModelo> polizas;
    
    /**
     * Creates new form Surax
     */
    public Surax(ArrayList<Object> data) {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/icon.png")).getImage());
        setTitle("Surax");
        this.data = data;
        this.personas = (ArrayList<PersonaModelo>) this.data.get(0);
        this.vehiculos = (ArrayList<VehiculoModelo>) this.data.get(1);
        this.estudiantes = (ArrayList<EstudianteModelo>) this.data.get(2);
        this.polizas = (ArrayList<PolizaModelo>) this.data.get(3);
    }
    
    private Surax() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void mostrarConsolidado(){
        jPanelInicial.setVisible(false);
        jPanelConsolidado.setVisible(true);
        icon.setVisible(false);
        String msj = "";
        for (PersonaModelo persona : this.personas) {
            msj += " Nombre: " + persona.getNombre() + "   ID: " +  persona.getId();
        }
        jLabel1.setText(msj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        jPanelInicial = new javax.swing.JPanel();
        btnEstudiantes = new javax.swing.JLabel();
        btnVehiculos = new javax.swing.JLabel();
        btnPersonas = new javax.swing.JLabel();
        msjIndicacion = new javax.swing.JLabel();
        btnConsolidado = new javax.swing.JLabel();
        jPanelConsolidado = new javax.swing.JPanel();
        btnVolver = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setFont(new java.awt.Font("Segoe UI Symbol", 0, 72)); // NOI18N
        icon.setForeground(new java.awt.Color(0, 174, 199));
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/icon.png"))); // NOI18N
        icon.setText("SuraX");
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanelInicial.setBackground(new java.awt.Color(255, 255, 255));

        btnEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/estudiantes_card.png"))); // NOI18N
        btnEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/vehiculos_card.png"))); // NOI18N
        btnVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVehiculosMouseClicked(evt);
            }
        });

        btnPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/personas_card.png"))); // NOI18N
        btnPersonas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonasMouseClicked(evt);
            }
        });

        msjIndicacion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        msjIndicacion.setForeground(new java.awt.Color(112, 112, 112));
        msjIndicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msjIndicacion.setText("Selecciona la modalidad de poliza a la que desea acceder");

        btnConsolidado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnConsolidado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConsolidado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/consolidado_info.png"))); // NOI18N
        btnConsolidado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsolidado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsolidadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelInicialLayout = new javax.swing.GroupLayout(jPanelInicial);
        jPanelInicial.setLayout(jPanelInicialLayout);
        jPanelInicialLayout.setHorizontalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicialLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(msjIndicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelInicialLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnPersonas)
                .addGap(36, 36, 36)
                .addComponent(btnVehiculos)
                .addGap(36, 36, 36)
                .addComponent(btnEstudiantes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsolidado)
                .addGap(106, 106, 106))
        );
        jPanelInicialLayout.setVerticalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicialLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnConsolidado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVehiculos)
                    .addGroup(jPanelInicialLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPersonas)
                            .addComponent(btnEstudiantes))))
                .addGap(40, 40, 40)
                .addComponent(msjIndicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanelInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        jPanelConsolidado.setBackground(java.awt.Color.white);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/surax/vista/images/back_icon.png"))); // NOI18N
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        btnVolver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnVolverKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sin Información");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanelConsolidadoLayout = new javax.swing.GroupLayout(jPanelConsolidado);
        jPanelConsolidado.setLayout(jPanelConsolidadoLayout);
        jPanelConsolidadoLayout.setHorizontalGroup(
            jPanelConsolidadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsolidadoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsolidadoLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanelConsolidadoLayout.setVerticalGroup(
            jPanelConsolidadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsolidadoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelConsolidado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonasMouseClicked
        Utils.pasarFrame(this, new PersonaVista(this.data));
    }//GEN-LAST:event_btnPersonasMouseClicked

    private void btnConsolidadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsolidadoMouseClicked
        mostrarConsolidado();
    }//GEN-LAST:event_btnConsolidadoMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        jPanelInicial.setVisible(true);
        jPanelConsolidado.setVisible(false);
        icon.setVisible(true);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnVolverKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverKeyPressed

    private void btnVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculosMouseClicked
        Utils.pasarFrame(this, new VehiculoVista());
    }//GEN-LAST:event_btnVehiculosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Surax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Surax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Surax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Surax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Surax().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnConsolidado;
    private javax.swing.JLabel btnEstudiantes;
    private javax.swing.JLabel btnPersonas;
    private javax.swing.JLabel btnVehiculos;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelConsolidado;
    private javax.swing.JPanel jPanelInicial;
    private javax.swing.JLabel msjIndicacion;
    // End of variables declaration//GEN-END:variables
}
